# Generated by Django 5.2.7 on 2025-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProxyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this routing rule', max_length=100)),
                ('regex', models.CharField(help_text='Regex used to match against local_alias in incoming request', max_length=255)),
                ('target_url', models.URLField(help_text='Base URL of the upstream policy server (e.g. https://upstream.example.com)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
