# Generated by Django 5.2.7 on 2025-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyproxyrule',
            options={},
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='basic_auth_password',
            field=models.CharField(blank=True, help_text='Optional password for Basic Auth', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='basic_auth_username',
            field=models.CharField(blank=True, help_text='Optional username for Basic Auth', max_length=255, null=True),
        ),
    ]
