# Generated by Django 5.2.7 on 2025-10-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0002_alter_policyproxyrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='target_url',
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='participant_target_url',
            field=models.URLField(blank=True, help_text='Base URL of the upstream *participant policy* server', null=True),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='service_target_url',
            field=models.URLField(blank=True, help_text='Base URL of the upstream *service config* policy server', null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PolicyRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField()),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy_router.policyproxyrule')),
            ],
        ),
    ]
