# Generated by Django 5.2.7 on 2025-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0003_remove_policyproxyrule_target_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrequestlog',
            name='request_headers',
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='participant_target_url',
            field=models.URLField(blank=True, help_text='Upstream participant policy URL', null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='regex',
            field=models.CharField(help_text='Regex used to match local_alias', max_length=255),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='service_target_url',
            field=models.URLField(blank=True, help_text='Upstream service policy URL', null=True),
        ),
        migrations.AlterField(
            model_name='policyrequestlog',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
