# Generated by Django 5.2.7 on 2025-10-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0004_remove_policyrequestlog_request_headers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyproxyrule',
            options={'ordering': ['priority', 'updated_at']},
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='Priority of the rule (lower values evaluated first)'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_password',
            field=models.CharField(blank=True, help_text='Optional password for Basic Auth', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_username',
            field=models.CharField(blank=True, help_text='Optional username for Basic Auth', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is enabled'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='participant_target_url',
            field=models.URLField(blank=True, help_text='Base URL of the upstream participant policy server', null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='regex',
            field=models.CharField(help_text='Regex used to match against local_alias in incoming request', max_length=255),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='service_target_url',
            field=models.URLField(blank=True, help_text='Base URL of the upstream service policy server', null=True),
        ),
    ]
