# Generated by Django 5.2.7 on 2025-10-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0005_alter_policyproxyrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyproxyrule',
            options={},
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='always_continue',
            field=models.BooleanField(default=False, help_text="If enabled, bypass upstream and return {'status': 'success', 'action': 'continue'}"),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='basic_auth_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers are matched first'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='regex',
            field=models.CharField(help_text='Regex used to match against local_alias in incoming request', max_length=255, verbose_name='local_alias regex'),
        ),
    ]
