# Generated by Django 5.2.7 on 2025-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0006_alter_policyproxyrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='always_continue',
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='always_continue_participant',
            field=models.BooleanField(default=False, help_text='Always return continue for participant policy'),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='always_continue_service',
            field=models.BooleanField(default=False, help_text='Always return continue for service policy'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='participant_target_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers match first'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='regex',
            field=models.CharField(help_text='Local alias regex to match incoming requests', max_length=255),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='service_target_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
