# Generated by Django 5.2.7 on 2025-10-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0007_remove_policyproxyrule_always_continue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrequestlog',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
    ]
