# Generated by Django 5.2.7 on 2025-10-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0008_policyrequestlog_is_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='always_continue_participant',
        ),
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='always_continue_service',
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='override_participant_response',
            field=models.JSONField(blank=True, default=dict, help_text='If set, this JSON will be returned for participant policy instead of proxying upstream', null=True),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='override_service_response',
            field=models.JSONField(blank=True, default=dict, help_text='If set, this JSON will be returned for service policy instead of proxying upstream', null=True),
        ),
    ]
