# Generated by Django 5.2.7 on 2025-10-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0009_remove_policyproxyrule_always_continue_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='always_continue_participant',
            field=models.BooleanField(default=False, help_text='Always return continue for participant policy'),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='always_continue_service',
            field=models.BooleanField(default=False, help_text='Always return continue for service policy'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='override_participant_response',
            field=models.TextField(blank=True, help_text='Custom JSON response for participant policy when override is enabled', null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='override_service_response',
            field=models.TextField(blank=True, help_text='Custom JSON response for service policy when override is enabled', null=True),
        ),
    ]
