# Generated by Django 5.2.7 on 2025-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0010_policyproxyrule_always_continue_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyproxyrule',
            name='override_participant_response',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='override_service_response',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
