# Generated by Django 5.2.7 on 2025-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0011_alter_policyproxyrule_override_participant_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('dial_in', 'Dial In'), ('dial_out', 'Dial Out'), ('non_dial', 'Non Dial')], help_text='Optional: restrict rule to a specific call direction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='protocol',
            field=models.CharField(blank=True, choices=[('api', 'API'), ('webrtc', 'WebRTC'), ('sip', 'SIP'), ('rtmp', 'RTMP'), ('h323', 'H.323'), ('teams', 'Microsoft Teams'), ('mssip', 'Microsoft SIP')], help_text='Optional: restrict rule to a specific protocol', max_length=20, null=True),
        ),
    ]
