# Generated by Django 5.2.7 on 2025-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0012_policyproxyrule_call_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrequestlog',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('dial_in', 'Dial In'), ('dial_out', 'Dial Out'), ('non_dial', 'Non Dial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policyrequestlog',
            name='protocol',
            field=models.CharField(blank=True, choices=[('api', 'API'), ('webrtc', 'WebRTC'), ('sip', 'SIP'), ('rtmp', 'RTMP'), ('h323', 'H.323'), ('teams', 'Teams'), ('mssip', 'MS-SIP')], max_length=20, null=True),
        ),
    ]
