# Generated by Django 5.2.7 on 2025-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0013_policyrequestlog_call_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='call_direction',
        ),
        migrations.RemoveField(
            model_name='policyproxyrule',
            name='protocol',
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='call_directions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='protocols',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
