# Generated by Django 5.2.7 on 2025-10-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0014_remove_policyproxyrule_call_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyproxyrule',
            name='call_directions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='protocols',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
