# Generated by Django 5.2.7 on 2025-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0015_alter_policyproxyrule_call_directions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyproxyrule',
            name='match_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
