# Generated by Django 5.2.7 on 2025-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0016_policyproxyrule_last_matched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='source_match',
            field=models.CharField(blank=True, help_text='Optional source IP or FQDN of the Infinity node. Leave blank to match any source.', max_length=255, null=True),
        ),
    ]
