# Generated by Django 5.2.7 on 2025-10-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0017_policyproxyrule_source_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='source_host',
            field=models.CharField(blank=True, help_text='Source IP or FQDN of the requesting Infinity node', max_length=255, null=True),
        ),
    ]
