# Generated by Django 5.2.7 on 2025-10-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0019_policyrequestlog_source_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrequestlog',
            name='request_body',
        ),
        migrations.AddField(
            model_name='policyrequestlog',
            name='request_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
