# Generated by Django 5.2.7 on 2025-10-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0020_remove_policyrequestlog_request_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyproxyrule',
            name='advanced_logic_enabled',
            field=models.BooleanField(default=False, help_text='Enable advanced logic editor for this rule (participant & service policies).'),
        ),
    ]
