# Generated by Django 5.2.7 on 2025-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_router', '0021_policyproxyrule_advanced_logic_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrequestlog',
            name='logic_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrequestlog',
            name='matched_logic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='advanced_logic_enabled',
            field=models.BooleanField(default=False, help_text='Enable advanced logic editor (participant & service policies).'),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='source_host',
            field=models.CharField(blank=True, help_text='Source host seen from request logs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyproxyrule',
            name='source_match',
            field=models.CharField(blank=True, help_text='Optional source IP/FQDN. Leave blank to match any source.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyrequestlog',
            name='call_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyrequestlog',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyrequestlog',
            name='source_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
