# Generated by Django 5.2.7 on 2025-10-26 04:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy_router', '0020_remove_policyrequestlog_request_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('participant', 'Participant'), ('service', 'Service')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.MinLengthValidator(0)])),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_logics', to='policy_router.policyproxyrule')),
            ],
            options={
                'indexes': [models.Index(fields=['rule', 'rule_type'], name='policy_engi_rule_id_4d8514_idx')],
                'unique_together': {('rule', 'rule_type')},
            },
        ),
    ]
