# Generated by Django 5.2.7 on 2025-10-25 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy_router', '0020_remove_policyrequestlog_request_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('participant', 'Participant'), ('service', 'Service')], max_length=20)),
                ('matched', models.BooleanField(default=False)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='policy_router.policyproxyrule')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('participant', 'Participant'), ('service', 'Service')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_logic', to='policy_router.policyproxyrule')),
            ],
            options={
                'ordering': ['rule_id', 'rule_type'],
                'unique_together': {('rule', 'rule_type')},
            },
        ),
    ]
