# Generated by Django 5.2.7 on 2025-10-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydecisionlog',
            name='call_direction',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='evaluation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='local_alias',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='participant_uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='protocol',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='remote_alias',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='remote_display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='policydecisionlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
