# Generated by Django 5.2.7 on 2025-10-29 22:09

import django.db.models.deletion
import policy_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0001_initial'),
        ('policy_router', '0022_policyrequestlog_logic_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylogic',
            name='conditions',
            field=models.JSONField(blank=True, default=policy_engine.models.default_conditions),
        ),
        migrations.AlterField(
            model_name='policylogic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='policylogic',
            name='response',
            field=models.JSONField(blank=True, default=policy_engine.models.default_response),
        ),
        migrations.AlterField(
            model_name='policylogic',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_logic', to='policy_router.policyproxyrule'),
        ),
    ]
