# Generated by Django 5.2.7 on 2025-10-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0002_policydecisionlog_call_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydecisionlog',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='policydecisionlog',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='policydecisionlog',
            name='rule_type',
            field=models.CharField(choices=[('service', 'Service'), ('participant', 'Participant')], max_length=32),
        ),
    ]
