# Generated by Django 5.2.7 on 2025-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0002_alter_policylogic_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylogic',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
