# Generated by Django 5.2.7 on 2025-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0003_policylogic_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylogic',
            name='action',
            field=models.CharField(choices=[('allow', 'Allow'), ('reject', 'Reject')], default='allow', max_length=10),
        ),
    ]
