# Generated by Django 5.2.7 on 2025-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0005_auto_20251102_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Identity Attribute',
                'verbose_name_plural': 'Identity Attributes',
            },
        ),
    ]
