# Generated by Django 5.2.7 on 2025-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0006_identityattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityattribute',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='identityattribute',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description shown in UI dropdowns and help tooltips.', max_length=255),
        ),
        migrations.AlterField(
            model_name='identityattribute',
            name='name',
            field=models.CharField(help_text="Just the attribute name, e.g. 'title', 'mail', 'department'", max_length=100, unique=True),
        ),
    ]
