# Generated by Django 5.2.7 on 2025-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0007_alter_identityattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=255)),
                ('attrs', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('subject',)},
            },
        ),
    ]
